name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.164.0/hugo_0.164.0_linux-amd64.tar.gz
          tar -xzf hugo_0.164.0_linux-amd64.tar.gz
          hugo build
      # - if: ${{ forgejo.event_name == 'push' && forgejo.event.ref == 'refs/heads/main' }}
      # uses: https://codeberg.org/git-pages/action@v2
      - uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/
          token: ${{ forge.token }}
          source: public/
