name: Publish
on:
  push:
jobs:
  publish:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v7
      - run: |
          hugo build
          mkdir _site
          cp *.html _site/
      - if: ${{ forgejo.event_name == 'push' && forgejo.event.ref == 'refs/heads/main' }}
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/
          token: ${{ forge.token }}
          source: _site/
